Naming a few boost related variables
sonicdcer/sf64 pull request #281
Opened 2024-12-29 23:28 UTC by Kiloku

For more clarity about `gTankActiveBurnerCount`: Each of the following actions increments the value if they are happening during the frame: Player is boosting, player is braking, player is using the left jet (holding Z), player is using the right jet (holding R). 
This value is used to determine how fast the boost meter should be drained.

2024-12-29 23:30 UTC, sonicdcer requested changes

2024-12-29 23:30 UTC, sonicdcer commented on src/engine/fox_tank.c
> +s32 gTankActiveBurnerCount = 0;
```suggestion
s32 sTankActiveBurnerCount = 0;

2024-12-30 00:06 UTC, Kiloku commented
How can I tell if a variable is static rather than global? I'm more used to C++ than C, so I'm kind of learning a lot still

2024-12-30 01:30 UTC, sonicdcer commented
> How can I tell if a variable is static rather than global? I'm more used to C++ than C, so I'm kind of learning a lot still
If it's used in only one file, that's an indication of a variable being static. We don't use the static keyword here however, because IDO removes them from the mapfile, and they're good to have for usage of various tools.

2024-12-30 01:30 UTC, sonicdcer approved these changes

2024-12-30 21:03 UTC, merged