Sector X Overlay Decompiled
sonicdcer/sf64 pull request #89
Opened 2024-01-16 16:10 UTC by KiritoDv

![image](https://github.com/sonicdcer/sf64/assets/36680385/c8186685-83df-49e1-a5da-9594622fe241)

DESTROY
DESTROY

2024-01-16 16:27 UTC, sonicdcer requested changes

2024-01-16 16:27 UTC, sonicdcer commented on src/overlays/ovl_i2/fox_sx.c
> +            if ((!(gFrameCount & 3)) && (Rand_ZeroOne() < 0.2f)) {
```suggestion
if (!(gFrameCount & 3)

2024-01-16 16:27 UTC, sonicdcer commented on src/overlays/ovl_i2/fox_sx.c
> +                *(gTeamShields + 2) = -2;
```suggestion
gTeamShields[2] = -2;

2024-01-16 16:47 UTC, sonicdcer approved these changes

2024-01-16 16:47 UTC, sonicdcer commented on src/overlays/ovl_i2/fox_sx.c
> +        default:
space

2024-01-16 16:47 UTC, sonicdcer commented on src/overlays/ovl_i2/fox_sx.c
> +    if (((arg0 >= 2) && (arg0 < 0xC)) || ((arg0 >= 0x20) && (arg0 < 0x24))) {
Decimal

2024-01-16 16:47 UTC, sonicdcer commented on src/overlays/ovl_i2/fox_sx.c
> +            if (D_80177A80 >= 0x12D) {
dec

2024-01-16 17:01 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +                        boss->fwork[42] = 0.0f;
decreasing order suggests chain assign. Does that work?

2024-01-16 17:01 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +                    boss->actionState = 0x55;
```suggestion
                    boss->actionState = 85;
```

2024-01-16 17:02 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +            if (boss->swork[1] >= 51) {
```suggestion
        if (boss->swork[1] > 40) {
            if (boss->swork[1] > 50) {
```

2024-01-16 17:02 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +    }
I think this should be else

2024-01-16 17:04 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +void func_i2_80193208(s32 arg0, Vec3f* arg1, void* ptr) {
Signature of a post limb draw should be `void func_i2_80193208(s32 limbIndex, Vec3f* rot, void* data)`, where data can be renamed to something more fitting.

2024-01-16 17:05 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +                func_8006EEFC(0x64, 0.0f, player->camEye.y + 50.0f, player->camEye.z + 20.0f, dest.x, dest.y, dest.z,
```suggestion
                func_8006EEFC(100, 0.0f, player->camEye.y + 50.0f, player->camEye.z + 20.0f, dest.x, dest.y, dest.z,
```

2024-01-16 17:07 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +            if (D_80177A80 == 0xAA) {
```suggestion
            if (D_80177A80 == 170) {
```
`D_80177A80` is also a frame counter, so should be decimal.

2024-01-16 17:08 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +    }
else?

2024-01-16 17:08 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +    actor->iwork[0xE] = D_i2_8019577C[arg1];
```suggestion
    actor->iwork[11] = 1;
    actor->iwork[14] = D_i2_8019577C[arg1];
```
work indices also in decimal

2024-01-16 17:10 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +                    D_800D3180[2] = Play_CheckMedalStatus(0x96U) + 1;
```suggestion
                    D_800D3180[2] = Play_CheckMedalStatus(150) + 1;
```

2024-01-16 17:10 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +            gActors[3].unk_0B8 = 0xA;
```suggestion
            gActors[3].unk_0B8 = 10;
```

2024-01-16 17:10 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +            player->timer_1F8 = 0x28;
```suggestion
            player->timer_1F8 = 40;
```

2024-01-16 17:13 UTC, petrie911 commented on src/overlays/ovl_i2/fox_sx.c
> +    Vec3f sp64 = D_i2_80195674;
```suggestion
    Vec3f sp64 = {0.0f, 0.0f, 0.0f};
```
This sort of thing is basically always a stack variable intializer. You'll have to move the data around to accommodate this.

2024-01-17 16:03 UTC, petrie911 approved these changes

2024-01-17 16:07 UTC, merged