Match Func i1 801922 dc
sonicdcer/sf64 pull request #94
Opened 2024-01-17 19:24 UTC by Vulto

2024-01-19 17:50 UTC, sonicdcer requested changes

2024-01-19 17:50 UTC, sonicdcer commented on src/overlays/ovl_i1/sf_ve1.c
> +}
```suggestion
void func_i1_801923C0(Object_4C* obj4C) {
    Boss* boss;
    s32 i;

    for (boss = &gBosses[0], i = 0; i < 4; i++, boss++) {
        if (boss->obj.status != 0 && boss->obj.id == OBJ_BOSS_319) {
            if (boss->obj.pos.z <= obj4C->obj.pos.z) {
                D_i1_8019C0BC = (s32)obj4C->obj.rot.x + 1;
                obj4C->obj.status = 0;
            }
            break;
        }
    }
}

2024-01-19 17:51 UTC, sonicdcer requested changes

2024-01-19 17:51 UTC, sonicdcer commented on src/overlays/ovl_i1/sf_ve1.c
> +}
```suggestion
void func_i1_801923C0(Object_4C* obj4C) {
    Boss* boss;
    s32 i;

    for (boss = &gBosses[0], i = 0; i < 4; i++, boss++) {
        if (boss->obj.status != 0 && boss->obj.id == OBJ_BOSS_319) {
            if (boss->obj.pos.z <= obj4C->obj.pos.z) {
                D_i1_8019C0BC = (s32)obj4C->obj.rot.x + 1;
                obj4C->obj.status = 0;
            }
            break;
        }
    }
}

2024-01-19 17:55 UTC, Vulto commented on src/overlays/ovl_i1/sf_ve1.c
> +}
Much better now. TY

2024-01-19 23:53 UTC, sonicdcer requested changes

2024-01-19 23:53 UTC, sonicdcer commented on src/overlays/ovl_i1/sf_ve1.c
> +}
https://decomp.me/scratch/EiXRu
```suggestion
f32 func_i1_801920F0(f32* arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32* arg5) {
    f32 temp;

    *arg5 = arg1 - *arg0;

    if (*arg5 > 180.0f) {
        do {
            *arg5 -= 360.0f;
        } while (*arg5 > 180.0f);
    } else if (*arg5 < -180.0f) {
        do {
            *arg5 += 360.0f;
        } while (*arg5 < -180.0f);
    }

    temp = *arg5;

    if (temp != 0.0f) {
        temp *= arg2;

        if ((arg4 <= temp) || ((temp <= -arg4))) {
            if (arg3 < temp) {
                temp = arg3;
            } else {

                if (-arg3 > temp) {
                    temp = -arg3;
                }
            }
            *arg0 += temp;
        } else {
            if (temp < arg4) {
                temp = arg4;
                *arg0 += arg4;

                if (arg1 < *arg0) {
                    *arg0 = arg1;
                }
            } else if (-arg4 < temp) {
                temp = -arg4;
                *arg0 += -arg4;

                if (*arg0 < arg1) {
                    *arg0 = arg1;
                }
            }
        }
    }

    if (*arg0 >= 360.0f) {
        *arg0 = *arg0 - 360.0f;
    } else if (*arg0 < 0.0f) {
        *arg0 = *arg0 + 360.0f;
    }

    return temp;
}

2024-01-19 23:53 UTC, sonicdcer commented on src/overlays/ovl_i1/sf_ve1.c
> +    Boss* boss = gBosses;
```suggestion
Boss* boss = &gBosses[0];

2024-01-19 23:53 UTC, sonicdcer commented on src/overlays/ovl_i1/sf_ve1.c
> +    Boss* boss = gBosses;
same for the other ones

2024-01-20 01:02 UTC, sonicdcer requested changes

2024-01-20 01:02 UTC, sonicdcer commented on src/overlays/ovl_i1/sf_ve1.c
> +    for (boss = &gBosses[0], i = 0; i < 4; i++, boss++) {
Space between declarations and code, full Style guide here:
https://github.com/sonicdcer/sf64/wiki/Style-guide

2024-01-20 01:02 UTC, sonicdcer commented on src/overlays/ovl_i1/sf_ve1.c
> +    Boss* boss = gBosses;
There are still others to fix, please don't use the apply suggestion button, you should do this manually.
```suggestion
Boss* boss = &gBosses[0];

2024-01-21 02:54 UTC, sonicdcer approved these changes

2024-01-21 02:54 UTC, merged